#!/usr/bin/env bash

# Show the command line of a process specified by PID.
# Does not work with the built-in bash in macOS. Install from homebrew.
# Examples:
#   $ cmdof 1
#   $ pgrep alacritty | cmdof
#   $ pgrep alacritty | cmdof - -n

set -e

if [[ ! -t 0 ]] && [[ $1 =~ ^-?$ ]]; then
    [[ $2 != -n ]] && verbose=1
    readarray -td$'\n' pid
else
    pid=("$@")
fi
for p in "${pid[@]}"; do
    (( verbose )) && printf '%s: ' "$p"
    ps -ww -p "$p" -o args=
done
