#!/bin/zsh

cd || true

args=(--title='Dropdown Terminal'
      --config-file $HOME/.config/alacritty/dropdown.toml
      -e sh -c "while true; do tmux new -A -s dropdown || break; done")

alacritty ${args[@]} &
