#!/bin/sh

# The dropdown terminal for my i3 config

# check if the dropdown terminal already exists
xdotool search --class Alacritty search --classname dropdown-terminal >/dev/null && exit

cd || true
alacritty --title=Dropdown --class=dropdown-terminal \
    -e sh -c 'while true; do tmux new -s dropdown || tmux attach -t dropdown || break; done' &
