#!/bin/sh
pgrep -u "$USER" -x i3lock && exit

set -e

if [ "$(dunstctl is-paused)" != true ]; then
    dunstctl set-paused true
    unpause=1
fi

unlock() {
    [ "$unpause" = 1 ] && dunstctl set-paused false
    xset -dpms
}

xset dpms force on
xset dpms 0 5 0
xset +dpms
trap 'unlock' EXIT

i3lock --nofork \
       --color=4c7899 \
       --ignore-empty-password \
       --show-failed-attempts
