#!/bin/sh

[ $# = 0 ] && exit 1

hascmd() {
    command -v "$1" >/dev/null
}

"$@"
ecode=$?

[ "$ecode" != 0 ] && ecodestr=" ($ecode)"
hascmd notify-send && notify-send "Command completed${ecodestr-}" "$*"
printf "\a"

exit "$ecode"
