#!/bin/sh

# Setup a rust doc server on port 9200, used
# by Rust Search Extension in firefox

port=9200
: "${RUSTUP_HOME:=$HOME/.rustup}"
toolchain="nightly-x86_64-unknown-linux-gnu"

case "$1" in
    -k)
        pkill -f "python -m http.server $port" && echo "Killed" || true
        ;;
    -s)
        if pgrep -f "python -m http.server $port" >/dev/null; then
            echo "On"
        else
            echo "Off"
        fi
        ;;
    *)
        pkill -f "python -m http.server $port" >/dev/null 2>&1
        setsid --fork timeout 5h python -m http.server "$port" \
            --directory "$RUSTUP_HOME/toolchains/$toolchain/share/doc/rust/html" \
            >/dev/null 2>&1
        ;;
esac
