#!/bin/sh

killall -q polybar

while pgrep -U "$(id -ru)" -x polybar >/dev/null; do sleep 1; done

polybar --list-monitors | while read -r line; do
    moni=${line%%:*}
    if expr "$line" : '.*primary' >/dev/null; then
        MONITOR="$moni" PRIMARY=1 TRAY_POS=right polybar top &
    elif [ "$1" != "-1" ]; then
        MONITOR="$moni" polybar top &
    fi
done
