#!/bin/bash

# Without arguments:
#   Count up from zero
#
# With arguments:
#   Count down for a specified time
#   Example (count down for 3 minutes and 30 seconds):
#     $ countdown 3m 30s

show_time() {
    local time hours minutes seconds
    time=$1
    hours=$((time / 3600))
    time=$((time % 3600))
    minutes=$((time / 60))
    seconds=$((time % 60))
    printf "\r%d:%02d:%02d" "$hours" "$minutes" "$seconds"
}

trap 'exit 0' INT
trap 'tput cnorm' EXIT
tput civis

if [ -z "$1" ]; then
    elapsed=0
    while true; do
        show_time "$elapsed"
        elapsed=$((elapsed + 1))
        sleep 1
    done
    exit 0
fi

shopt -s extglob

time=0

while [ -n "$1" ]; do
    case $1 in
        +([0-9]))
            parsed=$1
            ;;
        +([0-9])s)
            parsed=${1%s}
            ;;
        +([0-9])m)
            raw=${1%m}
            parsed=$((raw * 60))
            ;;
        +([0-9])h)
            raw=${1%h}
            parsed=$((raw * 3600))
            ;;
        +([0-9])d)
            raw=${1%d}
            parsed=$((raw * 86400))
            ;;
        *)
            echo >&2 "Invalid: '$1'"
            exit
            ;;
    esac
    time=$((time + parsed))
    shift
done

while [ "$time" -gt 0 ]; do
    time=$((time - 1))
    show_time "$time"
    sleep 1
done

date=$(date +%T)

printf "\r%s: Time is up\n" "$date"
notify-send --expire-time=0 'countdown' "$date: time is up"
