#!/bin/sh

# Extract URLs from stdin then copy or view it

action() {
    case "$1" in
        Copy)
            printf %s "$2" | xclip -selection clipboard
            exit
            ;;
        View) xdg-open "$2"; exit ;;
        Back) selected= ;;
        *) exit 0 ;;
    esac
}

if [ "$1" = -r ]; then
    urls=$(urlex -r | awk '!x[$0]++')
    shift
else
    urls=$(urlex | awk '!x[$0]++')
fi
[ -z "$urls" ] && exit

while true; do
    selected=$(echo "$urls" | rofi -dmenu -i -no-custom -p 'Select a URL')
    [ -z "$selected" ] && exit

    case "$1" in
        -c | --copy) action Copy "$selected" ;;
        -v | --view) action View "$selected" ;;
        *) # ask
            method=$(printf "View\nCopy\nBack\nQuit\n" |
                rofi -dmenu -i -no-custom -lines 6 -p 'Action' -mesg "$selected")
            [ -z "$method" ] && exit
            action "$method" "$selected"
            ;;
    esac
done
