#!/bin/sh

# Extract URLs from stdin then copy or view it

export LC_ALL=C

url_regex=$(cat <<'EOF'
((https?|ftp)://[^<>"'[:space:]]*|(www|ftp)[0-9]?\.[.0-9a-zA-Z-]+)[^.,;<>"'):[:space:]]?[^,<>"'[:space:]]*[^.,;<>"'):[:space:]，。；」]
EOF
)

if [ "$1" = -r ]; then
    # reverse
    urls=$(grep -oE "$url_regex" | tac | awk '!x[$0]++')
    shift
else
    urls=$(grep -oE "$url_regex" | awk '!x[$0]++')
fi
[ -z "$urls" ] && exit

action() {
    case "$1" in
        Copy) printf %s "$2" | xclip -selection clipboard; exit ;;
        View) "${BROWSER:-xdg-open}" "$2"; exit ;;
        Back) selected= ;;
        *) exit 0 ;;
    esac
}

while true; do
    selected=$(echo "$urls" | rofi -dmenu -i -no-custom -p 'Select a URL')
    [ -z "$selected" ] && exit

    case "$1" in
        -c | --copy) action Copy "$selected" ;;
        -v | --view) action View "$selected" ;;
        *) # ask
            method=$(printf "View\nCopy\nBack\nQuit\n" |
                rofi -dmenu -i -no-custom -lines 6 -p 'Action' \
                     -mesg "$(echo "$selected" | sed 's/&/&amp;/g')")
            [ -z "$method" ] && exit
            action "$method" "$selected"
            ;;
    esac
done
